Repository akeneo/pim-docs, pull requests merged in 2018-11, with the labels that each got.

#1039 Fix typos
  import_and_export_data/product-import.rst
Labels: to review

#1019 Update pim_application.rst
  cloud_edition/flexibility_mode/docs/pim_application.rst
Labels: to review

#1018 Update crontasks.rst
  cloud_edition/flexibility_mode/docs/crontasks.rst
Labels: to review

#1041 Merge 2.0 into 2.1
  install_pim/manual/crontab_tasks_ee.rst.inc
  manipulate_pim_data/rule/general_information_on_rule_format.rst
Labels: to merge

#1042 Merge 2.1 into 2.2
  cloud_edition/flexibility_mode/docs/crontasks.rst
  install_pim/manual/crontab_tasks_ee.rst.inc
  manipulate_pim_data/rule/general_information_on_rule_format.rst
Labels: to review

#1043 Merge 2.2 into 2.3
  cloud_edition/flexibility_mode/docs/crontasks.rst
  cloud_edition/flexibility_mode/docs/partner_starterkit.rst
  install_pim/manual/crontab_tasks_ee.rst.inc
  manipulate_pim_data/rule/general_information_on_rule_format.rst
Labels: to review

#1046 Update installation_docker.rst
  install_pim/docker/installation_docker.rst
Labels: Contribution, Improvement, to review

#1048 Update the links to use the Portal section of the Help Center
  cloud_edition/flexibility_mode/docs/composer_settings.rst
  cloud_edition/flexibility_mode/docs/overview.rst
  cloud_edition/flexibility_mode/docs/partner_starterkit.rst
  developer_guide/installation/docker/installation_docker.rst
  developer_guide/installation/installation_archive.rst.inc
  developer_guide/installation/partners_portal_archive.rst.inc
  developer_guide/migration/index.rst
Labels: Improvement, to review

#1055 Update project_creation.rst
  technical_overview/teamwork_assistant/project_creation.rst
Labels: to review
