Repository akeneo/pim-docs, pull requests merged in 2018-03, with the labels that each got.

#855 Update documentation according new way to query families
  manipulate_pim_data/rule/general_information_on_rule_format.rst
Labels: to review

#857 Remove deprecated doc for CustomEntityBundle
  design_pim/guides/create_a_reference_data_crud.rst
  technical_architecture/bundles/custom_entity_bundle/abstract_entities_and_repositories.rst
  technical_architecture/bundles/custom_entity_bundle/crud_interfaces.rst.inc
  technical_architecture/bundles/custom_entity_bundle/crud_managers.rst
  technical_architecture/bundles/custom_entity_bundle/index.rst
  technical_architecture/bundles/index.rst
Labels: Outdated, to review

#806 Fix selenium and firefox version in order to setup behat
  technical_architecture/best_practices/core/behat.rst
Labels: to review

#858 1.7 cloud 466
  cloud_edition/flexibility_mode/docs/composer_settings.rst
  cloud_edition/flexibility_mode/index.rst
Labels: to review

#867 Add 2.3 to the list of PIM versions
  conf.py
Labels: to review

#868 Remove versions from conf.py
  conf.py
Labels: to review

#869 Merge branch '1.0' into branch '1.1'
  conf.py
Labels: to merge

#870 Merge branch '1.1' into branch '1.2'
  conf.py
Labels: to merge

#871 Merge branch '1.2' into branch '1.3'
  conf.py
Labels: to merge

#872 Merge branch '1.3' into branch '1.4'
  conf.py
Labels: to merge

#873 Merge branch '1.4' into branch '1.5'
  conf.py
Labels: to merge

#874 Merge branch '1.5' into branch '1.6'
  conf.py
Labels: to merge

#875 Deprecate 1.6 documentation
  _themes/akeneo_rtd/layout.html
Labels: to review

#876 Merge branch '1.6' into branch '1.7'
  _themes/akeneo_rtd/layout.html
  conf.py
Labels: to review

#877 Merge branch '1.7' into branch '2.0'
  cloud_edition/flexibility_mode/docs/composer_settings.rst
  cloud_edition/flexibility_mode/index.rst
  conf.py
Labels: to merge

#878 Merge branch '2.0' into branch '2.1'
  cloud_edition/flexibility_mode/docs/composer_settings.rst
  cloud_edition/flexibility_mode/index.rst
  conf.py
  design_pim/guides/create_a_reference_data_crud.rst
  design_pim/guides/how_to_customize_menu.rst
  technical_architecture/bundles/custom_entity_bundle/abstract_entities_and_repositories.rst
  technical_architecture/bundles/custom_entity_bundle/crud_interfaces.rst.inc
  technical_architecture/bundles/custom_entity_bundle/crud_managers.rst
  technical_architecture/bundles/custom_entity_bundle/index.rst
  technical_architecture/bundles/index.rst
Labels: to review

#879 Merge branch '2.1' into branch '2.2'
  cloud_edition/flexibility_mode/docs/composer_settings.rst
  cloud_edition/flexibility_mode/index.rst
  conf.py
  design_pim/guides/create_a_reference_data_crud.rst
  design_pim/guides/how_to_customize_menu.rst
  technical_architecture/bundles/custom_entity_bundle/abstract_entities_and_repositories.rst
  technical_architecture/bundles/custom_entity_bundle/crud_interfaces.rst.inc
  technical_architecture/bundles/custom_entity_bundle/crud_managers.rst
  technical_architecture/bundles/custom_entity_bundle/index.rst
  technical_architecture/bundles/index.rst
Labels: to merge

#880 Merge 2.2 into master
  cloud_edition/flexibility_mode/docs/composer_settings.rst
  conf.py
  design_pim/guides/create_a_reference_data_crud.rst
  design_pim/guides/how_to_customize_menu.rst
  technical_architecture/bundles/custom_entity_bundle/abstract_entities_and_repositories.rst
  technical_architecture/bundles/custom_entity_bundle/crud_interfaces.rst.inc
  technical_architecture/bundles/custom_entity_bundle/crud_managers.rst
  technical_architecture/bundles/custom_entity_bundle/index.rst
  technical_architecture/bundles/index.rst
Labels: to merge

#882 Update installation_docker.rst
  developer_guide/installation/docker/installation_docker.rst
Labels: to review

#887 Update the Migrate PIM Page
  migrate_pim/index.rst
Labels: to review

#888 Issue 725: Fix broken link on UI customization
  import_and_export_data/guides/create-connector.rst
Labels: to review

#889 Merge branch '1.7' into branch '2.0'
  install_pim/docker/installation_docker.rst
Labels: to merge

#890 Merge 2.0 into 2.1
  _themes/akeneo/layout.html
  import_and_export_data/guides/create-connector.rst
  install_pim/docker/installation_docker.rst
  install_pim/manual/system_requirements/system_install_ubuntu_1604.rst
  migrate_pim/index.rst
Labels: to merge
