Repository akeneo/pim-docs, pull requests merged in 2018-04, with the labels that each got.

#891 Add a deprecation notice on 2.1
  _themes/akeneo/layout.html
  _themes/akeneo/static/css/variables-43bf553955.css
Labels: to review

#893 Merge branch '2.1' into branch '2.2'
  _themes/akeneo/layout.html
  _themes/akeneo/static/css/variables-43bf553955.css
  import_and_export_data/guides/create-connector.rst
  install_pim/docker/installation_docker.rst
  install_pim/manual/system_requirements/system_install_ubuntu_1604.rst
  migrate_pim/index.rst
Labels: to merge

#895 Merge branch '2.2' into branch '2.3'
  _themes/akeneo/layout.html
  _themes/akeneo/static/css/variables-43bf553955.css
  import_and_export_data/guides/create-connector.rst
  install_pim/docker/installation_docker.rst
  install_pim/manual/system_requirements/system_install_ubuntu_1604.rst
  migrate_pim/index.rst
Labels: to merge

#896 Merge branch '2.3' into branch 'master'
  _themes/akeneo/layout.html
  _themes/akeneo/static/css/variables-43bf553955.css
  import_and_export_data/guides/create-connector.rst
  install_pim/docker/installation_docker.rst
  install_pim/manual/system_requirements/system_install_ubuntu_1604.rst
  migrate_pim/index.rst
Labels: to merge

#892 Remove deprecated ProductValue override doc
  manipulate_pim_data/catalog_structure/index.rst
  manipulate_pim_data/catalog_structure/overriding_the_orm_product_value.rst
Labels: Outdated

#881 Update documentation 22
  import_and_export_data/product-import.rst
  import_and_export_data/simple-import.rst
  manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst
  manipulate_pim_data/product/query.rst
  technical_architecture/best_practices/core/behat.rst
  technical_architecture/best_practices/core/conventions.rst
  technical_architecture/best_practices/index.rst
  technical_architecture/best_practices/reusable_bundle.rst
  technical_architecture/component-or-bundle.rst.inc
  technical_architecture/index.rst
Labels: wip

#899 Rename the property setter service name for 2.0
  manipulate_pim_data/rule/add_custom_action_rule_engine.rst
Labels: to review

#901 Merge 2.2 into 2.3
  import_and_export_data/product-import.rst
  import_and_export_data/simple-import.rst
  manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst
  manipulate_pim_data/product/query.rst
  technical_architecture/best_practices/core/behat.rst
  technical_architecture/best_practices/core/conventions.rst
  technical_architecture/best_practices/index.rst
  technical_architecture/best_practices/reusable_bundle.rst
  technical_architecture/component-or-bundle.rst.inc
  technical_architecture/index.rst
Labels: to review

#902 Fix deprecation notice on 1.6
  _themes/akeneo_rtd/layout.html
Labels: to review

#905 Merge branch '2.0' into branch '2.1'
  manipulate_pim_data/catalog_structure/index.rst
  manipulate_pim_data/catalog_structure/overriding_the_orm_product_value.rst
  manipulate_pim_data/rule/add_custom_action_rule_engine.rst
Labels: to review

#906 Merge branch '2.1' into branch '2.2'
  manipulate_pim_data/catalog_structure/index.rst
  manipulate_pim_data/catalog_structure/overriding_the_orm_product_value.rst
  manipulate_pim_data/rule/add_custom_action_rule_engine.rst
Labels: to merge

#907 Merge branch '2.2' into branch '2.3'
  manipulate_pim_data/catalog_structure/index.rst
  manipulate_pim_data/catalog_structure/overriding_the_orm_product_value.rst
  manipulate_pim_data/rule/add_custom_action_rule_engine.rst
Labels: to merge

#908 Merge branch '2.3' into branch 'master'
  README.md
  import_and_export_data/product-import.rst
  import_and_export_data/simple-import.rst
  install_pim/docker/installation_docker.rst
  manipulate_pim_data/catalog_structure/index.rst
  manipulate_pim_data/catalog_structure/overriding_the_orm_product_value.rst
  manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst
  manipulate_pim_data/product/query.rst
  manipulate_pim_data/rule/add_custom_action_rule_engine.rst
  technical_architecture/best_practices/core/conventions.rst
  technical_architecture/best_practices/index.rst
  technical_architecture/best_practices/reusable_bundle.rst
  technical_architecture/component-or-bundle.rst.inc
  technical_architecture/index.rst
Labels: to review

#914 Merge branch '2.2' into branch '2.3'
  install_pim/docker/installation_docker.rst
  manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst
Labels: to review

#918 Merge branch '1.6' into branch '1.7'
  developer_guide/installation/docker/installation_docker.rst
Labels: to review

#919 Merge branch '1.7' into branch '2.0'
  cloud_edition/flexibility_mode/docs/partner_starterkit.rst
  cloud_edition/flexibility_mode/docs/requirements.rst
  cloud_edition/flexibility_mode/index.rst
  install_pim/docker/installation_docker.rst
Labels: to review

#920 Merge branch '2.0' into branch '2.1'
  cloud_edition/flexibility_mode/docs/partner_starterkit.rst
  cloud_edition/flexibility_mode/docs/requirements.rst
  cloud_edition/flexibility_mode/index.rst
  install_pim/docker/installation_docker.rst
  install_pim/manual/crontab_tasks.rst.inc
  install_pim/manual/crontab_tasks_ee.rst.inc
Labels: to review

#922 Merge branch '2.2' into branch '2.3'
  cloud_edition/flexibility_mode/docs/partner_starterkit.rst
  cloud_edition/flexibility_mode/docs/requirements.rst
  cloud_edition/flexibility_mode/index.rst
  install_pim/manual/crontab_tasks.rst.inc
  install_pim/manual/crontab_tasks_ee.rst.inc
Labels: to merge

#923 Merge branch '2.3' into branch 'master'
  cloud_edition/flexibility_mode/docs/partner_starterkit.rst
  cloud_edition/flexibility_mode/docs/requirements.rst
  cloud_edition/flexibility_mode/index.rst
  install_pim/docker/installation_docker.rst
  install_pim/manual/crontab_tasks.rst.inc
  install_pim/manual/crontab_tasks_ee.rst.inc
  manipulate_pim_data/mass_edition/register_a_new_mass_edit_action.rst
  manipulate_pim_data/product_asset/asset.csv
Labels: to review

#924 Update automate-import-exports.rst
  import_and_export_data/guides/automate-import-exports.rst
Labels: to review

#928 Cloud-628: Add page for custom cron tasks in flexibility
  cloud_edition/flexibility_mode/docs/crontasks.rst
  cloud_edition/flexibility_mode/docs/pim_application.rst
  cloud_edition/flexibility_mode/index.rst
Labels: to review
