Repository akeneo/pim-docs, pull requests merged in 2022-02, with the labels that each got.

#1642 remove duplicate zip package
  install_pim/manual/system_requirements/manual_system_installation_debian10.rst
Labels: Contribution

#1726 BH-986: Merge 6.0 into master
  .circleci/config.yml
Labels: pullup

#1732 Merge 5.0 into 6.0
  Dockerfile
  cloud_edition/flexibility_mode/docs/job_consumers_and_workers.rst
  contribute_to_pim/report_bug.rst.inc
  install_pim/docker/installation_docker.rst
  maintain_pim/first_aid_kit/index.rst
Labels: pullup

#1736 Pull up 6.0 to master
  migrate_pim/upgrade/upgrade_from_40_to_50.rst
  migrate_pim/upgrade/upgrade_from_50_to_60.rst
Labels: pullup

#1737 Update prerequisites for Onboarder (6.0 not supported yet)
  onboarder/prerequisites/index.rst
Labels: to review
